### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [DataBiosphere/data-browser#3229]
### Tasks
- [x] [Add axios and related error handling to remaining API calls](https://github.com/clevercanary/data-explorer/issues/107)
- [x] [Implement error handling](https://github.com/DataBiosphere/data-browser/issues/3175)
- [x] [Update Error component to match mocks ](https://github.com/clevercanary/data-explorer/issues/117)

**Comment by NoopDog** [comment]
Complete
