### ISSUE TITLE
Filter by age range

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [DataBiosphere/data-browser#3230]
#### Tasks
- [x] https://github.com/clevercanary/cc-design/issues/28
- [ ] https://github.com/DataBiosphere/findable-ui/issues/19
- [ ] https://github.com/DataBiosphere/data-browser/issues/3411
