### ISSUE TITLE
[DX] Download manifest from search results

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [DataBiosphere/data-browser#3236]
- [x] [[Findable] Download manifest from search results](https://github.com/DataBiosphere/findable-ui/issues/14)
- [x] [[Findable] Display summary on export search results](https://github.com/DataBiosphere/findable-ui/issues/33)
- [x] [[Findable] Display query on export search results](https://github.com/DataBiosphere/findable-ui/issues/32)
- [x] [[Findable] Select file type on export](https://github.com/DataBiosphere/findable-ui/issues/25)
- [x] [[Findable] Select species on export](https://github.com/DataBiosphere/findable-ui/issues/23)
- [x] [[HCA DB] Download manifest from search results](https://github.com/DataBiosphere/data-browser/issues/3238)

**Comment by MillenniumFalconMechanic** [comment]
Completed.
