### ISSUE TITLE
[HCA DB] Download search results via curl

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [DataBiosphere/data-browser#3243]
#### Depends On
- [x] [[Findable] Download search results via curl](https://github.com/DataBiosphere/findable-ui/issues/15)
- [x] [[Findable] Display summary on export search](https://github.com/DataBiosphere/findable-ui/issues/33)
- [x] [[Findable] Display query on export search results](https://github.com/DataBiosphere/findable-ui/issues/32)
- [x] [[Findable] Select file type on export](https://github.com/DataBiosphere/findable-ui/issues/25)
- [x] [[Findable] Select species on export](https://github.com/DataBiosphere/findable-ui/issues/23)

#### Approach
Configure the following:

1. Download manifest
2. File type selection
3. Species selection
4. Search query
5. Search summary
