### ISSUE TITLE
[DX] Export entity to Terra

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [DataBiosphere/data-browser#3247]
- [x] [[Findable] Implement export entity to Terra](https://github.com/DataBiosphere/findable-ui/issues/27)
- [x] [[AnVIL DX] Implement export dataset to Terra](https://github.com/DataBiosphere/data-browser/issues/3223)
- [x] [[HCA DB] Implement export project to Terra](https://github.com/DataBiosphere/data-browser/issues/3224)

**Comment by MillenniumFalconMechanic** [comment]
Completed.
