### ISSUE TITLE
Feedback and support

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [DataBiosphere/data-browser#3258]
#### Tasks
- [x] [[Findable] "Feedback & Support" button](https://github.com/clevercanary/cc-design/issues/31)
- [x] [[Findable] Feedback form](https://github.com/DataBiosphere/findable-ui/issues/18)
- [x] [[HCA DB] Feedback form](https://github.com/DataBiosphere/data-browser/issues/3260)

**Comment by MillenniumFalconMechanic** [comment]
Completed.
