### ISSUE TITLE
[DX] Google Analytics 4

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [DataBiosphere/data-browser#3261]
#### Tasks
- [x] [[DX] Document analytics requirements](https://github.com/DataBiosphere/data-browser/issues/3267)
- [x] [[AnVIL DX] Configure GA4 ](https://github.com/DataBiosphere/data-browser/issues/3268)
- [x] [[HCA DB] Configure GA4](https://github.com/DataBiosphere/data-browser/issues/3262)
- [x] Configure HCA DP
- [x] Configure HCA DB
- [x] [[AnVIL DX] Create GA4 reports](https://github.com/DataBiosphere/data-browser/issues/3269)
- [x] [[HCA DB] Configure GA4 reports](https://github.com/DataBiosphere/data-browser/issues/3270)
- [x] [[HCA Portal] Configure GA4](https://github.com/DataBiosphere/data-portal/issues/2099)
- [x] [[HCA Portal] Create GA4 reports](https://github.com/DataBiosphere/data-portal/issues/2100)

**Comment by NoopDog** [comment]
Complete
