### ISSUE TITLE
[DX] Testing

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [DataBiosphere/data-browser#3265]
#### Tasks
- [ ] [[DX] Increate Jest coverage of components - April](https://github.com/DataBiosphere/data-browser/issues/3266)
- [ ] [[DX] Increate Jest coverage of components - May](https://github.com/databiosphere/data-browser/issues/3329)
- [ ] [[DX] Increate Jest coverage of components - June](https://github.com/databiosphere/data-browser/issues/3330)
- [ ] [[DX] Create Playwright smoke test](https://github.com/DataBiosphere/data-browser/issues/3276)
- [ ] [[DX] Enhance E2E Playwright smoke test for new features - May](https://github.com/databiosphere/data-browser/issues/3331)
- [ ] [[DX] Enhance E2E Playwright smoke test for new features - June](https://github.com/databiosphere/data-browser/issues/3332)
- [ ] [[DX] Run Playwright smoke test on GitHub Actions onPush](https://github.com/DataBiosphere/data-browser/issues/3277)
- [ ] [[DX] Add E2E login/auth tests](https://github.com/databiosphere/data-browser/issues/3333)

**Comment by MillenniumFalconMechanic** [comment]
Closing epic.
