### ISSUE TITLE
[DX] Security and maintenance

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [DataBiosphere/data-browser#3310]
- [ ] [Update content security policy headers ](https://github.com/databiosphere/data-browser/issues/3320)
- [ ] [Fix security/audit findings - April](https://github.com/databiosphere/data-browser/issues/3311)
- [ ] [Fix security/audit findings - May](https://github.com/databiosphere/data-browser/issues/3312)
- [ ] [Fix security/audit findings - June](https://github.com/databiosphere/data-browser/issues/3313)
- [ ] [Triage monthly security findings - April ](https://github.com/databiosphere/data-browser/issues/3314)
- [ ] [Triage monthly security findings - May](https://github.com/databiosphere/data-browser/issues/3315)
- [ ] [Triage monthly security findings - June](https://github.com/databiosphere/data-browser/issues/3316)
- [ ] [NPM package version updates - April](https://github.com/databiosphere/data-browser/issues/3317)
- [ ] [NPM package version updates - May](https://github.com/databiosphere/data-browser/issues/3318)
- [ ] [NPM package version updates - June](https://github.com/databiosphere/data-browser/issues/3319)

**Comment by MillenniumFalconMechanic** [comment]
Completed.
