### ISSUE TITLE
[DX] Register and login

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [DataBiosphere/data-browser#3338]
#### Tasks
- [x] [[Findable] Terms of Service UI](https://github.com/clevercanary/cc-design/issues/37)
- [x] [[Findable] Terms of Service Stub](https://github.com/DataBiosphere/findable-ui/issues/20)
- [x] [[AnVIL DX] Implement Terms of Service](https://github.com/DataBiosphere/data-browser/issues/3412)
- [x] [[AnVIL Portal] Terms of Service](https://github.com/anvilproject/anvil-portal/issues/2697)
- [x] [[AnVIL DX] Implement logout](https://github.com/DataBiosphere/findable-ui/issues/21)
- [x] [[AnVIL DX] Validate login in dev and prod](https://github.com/databiosphere/data-browser/issues/3399)
- [x] [[AnVIL DX] Terms of Service Acceptance - Data Explorer](https://github.com/DataBiosphere/data-browser/issues/3407)
- [x] [[AnVIL DX] Terms of Service Acceptance - Terra ](https://github.com/DataBiosphere/data-browser/issues/3408)
- [x] [[AnVIL DX] Notify user if they need to create a Terra account](https://github.com/databiosphere/data-browser/issues/3401)
- [x] [[AnVIL DX] Instruct user to link eRA commons account to their Terra account](https://github.com/DataBiosphere/data-browser/issues/3402)
- [x] [[AnVIL DX] Notify user of eRA commons/Terra expiration (Design)](https://github.com/clevercanary/cc-design/issues/44)
- [x] [[AnVIL DX] Notify user of eRA commons/Terra expiration](https://github.com/databiosphere/data-browser/issues/3403)
- [x] [AC-11 Implement session inactivity logout](https://github.com/DataBiosphere/data-browser/issues/2885)
- [ ] [[DX] AC-10 Concurrent Session Control ](https://github.com/DataBiosphere/data-browser/issues/3339)

**Comment by NoopDog** [comment]
Complete.
