### ISSUE TITLE
[HCA DX] Track clicks on individual file download

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [DataBiosphere/data-browser#4244]
#### Depends On
[Add tracking of file download](https://github.com/DataBiosphere/findable-ui/issues/260)

#### Need
We need to add tracking of the individual file download to monitor user interactions and optimize conversions. This tracking will allow us to analyze the conversion funnel more accurately, ensuring that the file download is performing as expected.

#### Approach
* Configure custom `file_downloaded` event in GTM (variables, tags and triggers). 

#### Definition of Done
File download event is accessible in Query Explorer for dev and prod:

- [x] data.humancellatlas.org - GA4
- [x] data.humancellatlas.dev.clevercanary.com - GA4

**Comment by mrtopsyt** [comment]
#### Todo:
- [x] Add event to findable-ui (https://github.com/DataBiosphere/findable-ui/pull/263)
- [x] Release Findable with new event (https://github.com/DataBiosphere/findable-ui/pull/262)
- [x] Update data-brower to new findable-ui release
- [x] Deploy data-browser to prod
- [x] Create GTM Tags
- [x] Deploy GTM version to prod ([Version 64](https://tagmanager.google.com/#/versions/accounts/4492049679/containers/10468455/versions/64))

**Comment by MillenniumFalconMechanic** [comment]
#64 LGTM, thanks @jpaten!

**Comment by mrtopsyt** [comment]
@MillenniumFalconMechanic Working on staging and prod!

Prod:
<img width="518" alt="Screenshot 2024-11-29 at 3 47 51 PM" src="https://github.com/user-attachments/assets/165bc1a4-a5e3-4759-87c4-d54496be4b7f">
(I wonder who the 1 user is lol)

Staging:
![Image](https://github.com/user-attachments/assets/15e40548-b7f3-4955-8531-1947ef9e183e)

**Comment by MillenniumFalconMechanic** [comment]
Brilliant, thanks @jpaten!
