### ISSUE TITLE
[LungMAP DX] Track clicks on individual file download

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [DataBiosphere/data-browser#4245]
#### Depends On
[Add tracking of file download](https://github.com/DataBiosphere/findable-ui/issues/260)

#### Need
We need to add tracking of the individual file download to monitor user interactions and optimize conversions. This tracking will allow us to analyze the conversion funnel more accurately, ensuring that the file download is performing as expected.

#### Approach
* Configure custom `file_downloaded` event in GTM (variables, tags and triggers). 

#### Definition of Done
File download event is accessible in Query Explorer for dev and prod:

- [x] data-browser.lungmap.net - GA4
- [x] data-browser.dev.lungmap.net - GA4

**Comment by mrtopsyt** [comment]
#### Todo:
- [x] Add event to findable-ui (https://github.com/DataBiosphere/findable-ui/pull/263)
- [x] Release Findable with new event (https://github.com/DataBiosphere/findable-ui/pull/262)
- [x] Update data-brower to new findable-ui release
- [ ] Deploy data-browser to prod
- [x] Create GTM Tags
- [ ] Deploy GTM version to prod ([Version 64](https://tagmanager.google.com/#/versions/accounts/4492049679/containers/10468455/versions/64))

**Comment by MillenniumFalconMechanic** [comment]
#64 LGTM, thanks @jpaten!

**Comment by mrtopsyt** [comment]
Currently blocked, waiting on Findable 15.0.0 or later to be deployed to prod

**Comment by mrtopsyt** [comment]
@MillenniumFalconMechanic finally working!

Prod:
<img width="498" alt="Screenshot 2024-12-12 at 10 13 35 PM" src="https://github.com/user-attachments/assets/a263154b-aff2-4fc8-a459-07a4bae701c0" />

Staging:
<img width="501" alt="Screenshot 2024-12-12 at 10 15 36 PM" src="https://github.com/user-attachments/assets/7baa5b1e-03f7-4092-9508-f580ba5ec45b" />

**Comment by MillenniumFalconMechanic** [comment]
Thanks Jonah!
