### ISSUE TITLE
[AnVIL DX] Track clicks on individual file download

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [DataBiosphere/data-browser#4246]
#### Depends On
[Add tracking of file download](https://github.com/DataBiosphere/findable-ui/issues/260)

#### Need
We need to add tracking of the individual file download to monitor user interactions and optimize conversions. This tracking will allow us to analyze the conversion funnel more accurately, ensuring that the file download is performing as expected.

#### Approach
* Configure custom `file_downloaded` event in GTM (variables, tags and triggers). 

#### Definition of Done
File download event is accessible in Query Explorer for dev and prod:

- [x] AnVIL DX - GA4
- [x] AnVIL DX CC Staging - GA4

**Comment by mrtopsyt** [comment]
#### Todo:
- [x] Add event to findable-ui (https://github.com/DataBiosphere/findable-ui/pull/263)
- [x] Release Findable with new event (https://github.com/DataBiosphere/findable-ui/pull/262)
- [x] Update data-brower to new findable-ui release
- [x] Deploy data-browser to prod
- [x] Create GTM Tags
- [ ] Depoly GTM Tags to prod ([Version 9](https://tagmanager.google.com/#/versions/accounts/6001018596/containers/122744496/versions/9))

**Comment by MillenniumFalconMechanic** [comment]
#9 LGTM, thanks @jpaten!

**Comment by mrtopsyt** [comment]
Working on Staging - all set up but hasn't propagated to prod for some reason

<img width="493" alt="Screenshot 2024-12-02 at 3 22 59 PM" src="https://github.com/user-attachments/assets/d565b683-0d69-4ccf-8bab-5e2317ec0463">

**Comment by mrtopsyt** [comment]
@MillenniumFalconMechanic Now working on prod too! Should be good to go

![Image](https://github.com/user-attachments/assets/627aaa1d-85c7-46e6-8d0e-7c7337d1e724)

**Comment by MillenniumFalconMechanic** [comment]
Thanks Jonah!
